FROM ubuntu:24.04

WORKDIR /workspace

COPY requirements.txt requirements.txt
COPY Makefile Makefile
COPY lib/fprime lib/fprime
COPY lib/zephyr-workspace/zephyr/scripts/requirements.txt lib/zephyr-workspace/zephyr/scripts/requirements.txt

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    curl \
    make && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

RUN make fprime-venv
