FROM ubuntu:24.04

WORKDIR /workspace

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    curl \
    make && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

COPY requirements.txt requirements.txt
COPY Makefile Makefile
COPY lib/fprime lib/fprime
COPY lib/zephyr-workspace/zephyr/scripts/requirements-base.txt lib/zephyr-workspace/zephyr/scripts/requirements-base.txt
COPY lib/zephyr-workspace/zephyr/scripts/requirements-build-test.txt lib/zephyr-workspace/zephyr/scripts/requirements-build-test.txt
COPY lib/zephyr-workspace/zephyr/scripts/requirements-run-test.txt lib/zephyr-workspace/zephyr/scripts/requirements-run-test.txt

RUN make fprime-venv
