name: Bug Report
description: Report a bug in the PROVES Core Reference F Prime Zephyr implementation
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: dropdown
    id: target-board
    attributes:
      label: Target Board/Platform
      description: Which board or platform are you using?
      options:
        - proves_flight_control_board_v5c/rp2350a/m33
        - proves_flight_control_board_v5d/rp2350a/m33
        - proves_flight_control_board_v5/rp2350a/m33
        - Raspberry Pi Pico 2
        - STM32 (specify in description)
        - Other (specify in description)
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the bug
      placeholder: |
        1. Run 'make build'
        2. Flash firmware to board
        3. Connect GDS with 'make gds'
        4. Send command XYZ
        5. Observe error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The command should execute successfully and return telemetry data...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: The command failed with error code 5, and the board reset...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste any relevant logs, error messages, or console output
      placeholder: |
        ```
        Paste logs here...
        ```
      render: shell

  - type: dropdown
    id: component-affected
    attributes:
      label: Component Affected
      description: Which part of the system is affected by this bug?
      multiple: true
      options:
        - Deployment (ReferenceDeployment)
        - Topology (component connections)
        - Active Component (AntennaDeployer, BootloaderTrigger, etc.)
        - Passive Component
        - Driver Component (Drv/)
        - Build System (CMakeLists.txt, Makefile)
        - Integration/Testing (GDS, pytest)
        - Zephyr Configuration (prj.conf, Kconfig)
        - FPP Definition Files
        - Hardware/Board Configuration
        - Documentation
        - Other (specify in description)
    validations:
      required: true

  - type: input
    id: fprime-version
    attributes:
      label: F Prime Version
      description: Which version of F Prime are you using? (check lib/fprime/)
      placeholder: v4.0.0a1

  - type: input
    id: zephyr-version
    attributes:
      label: Zephyr Version
      description: Which version of Zephyr are you using? (check west.yml)
      placeholder: v4.2.0

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (environment, configuration changes, etc.)
      placeholder: This issue started after updating to the latest main branch...
