name: "Feature request"
description: "Suggest an enhancement or new feature."
title: "[FEATURE] {summary}"
labels:
  - "enhancement"
body:
  - type: markdown
    attributes:
      value: |
        ## Feature request
        Please describe the feature you'd like and why it would be useful.
  - type: input
    id: summary
    attributes:
      label: "Short summary"
      description: "Concise title for the feature request."
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: "Motivation and user story"
      description: "Who benefits and how will it be used?"
  - type: textarea
    id: proposal
    attributes:
      label: "Proposed implementation"
      description: "Any ideas for how it could be implemented (optional)."
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - "Low"
        - "Medium"
        - "High"
      description: "How important is this feature to you?"
